use_sim_time: false

odom_frame_id: "odom"
base_frame_id: "base_footprint"
global_frame_id: "map"

# Laser scan topic configuration
scan_topic: "/scan"
scan_frame_id: "base_scan"

update_min_d: 0.2  # Lower = more frequent updates
update_min_a: 0.2

min_particles: 500
max_particles: 2000

resample_interval: 1
transform_tolerance: 0.5

kld_err: 0.01
kld_z: 0.99

laser_max_range: 12.0
laser_min_range: 0.1
laser_model_type: "likelihood_field"
laser_z_hit: 0.95
laser_z_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.05
laser_sigma_hit: 0.2
laser_lambda_short: 0.1

odom_model_type: "diff"
odom_alpha1: 0.1
odom_alpha2: 0.1
odom_alpha3: 0.05
odom_alpha4: 0.05
odom_alpha5: 0.0

initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0
initial_cov_xx: 0.5
initial_cov_yy: 0.5
initial_cov_aa: 0.5
