amcl:
  ros__parameters:
    use_sim_time: False
    # Robot motion model parameters (differential drive)
    alpha1: 0.1  # Expected noise in odometry's rotation estimate from rotation
    alpha2: 0.1  # Expected noise in odometry's rotation estimate from translation
    alpha3: 0.1  # Expected noise in odometry's translation estimate from translation
    alpha4: 0.1  # Expected noise in odometry's translation estimate from rotation
    alpha5: 0.1  # Translation-related noise parameter
    
    # Frame IDs
    base_frame_id: "base_link"
    global_frame_id: "map"
    odom_frame_id: "odom"
    
    # Laser model parameters
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: true  # Skip beams for more robust operation
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 12.0
    laser_min_range: 0.15
    laser_model_type: "likelihood_field"  # Better for static environments
    max_beams: 100  # Increased for better accuracy
    
    # Particle filter parameters
    max_particles: 3000  # Increased for better accuracy
    min_particles: 500
    pf_err: 0.01  # Reduced error threshold
    pf_z: 0.99
    
    # Recovery behavior
    recovery_alpha_fast: 0.1  # Increased for faster recovery
    recovery_alpha_slow: 0.001  # Increased for better recovery
    resample_interval: 1
    
    # Robot model
    robot_model_type: "differential"
    
    # Particle cloud publishing
    publish_particles: true
    particle_filter_update_rate: 5.0
    transform_tolerance: 0.5
    
    # Update and transform parameters
    save_pose_rate: 0.5
    sigma_hit: 0.1  # Reduced for more precise measurements
    tf_broadcast: true
    transform_tolerance: 0.5  # Reduced for more timely transforms
    update_min_a: 0.1  # Reduced for more frequent updates on rotation
    update_min_d: 0.1  # Reduced for more frequent updates on translation
    
    # Sensor model weights
    z_hit: 0.8  # Increased for more weight on actual measurements
    z_max: 0.05
    z_rand: 0.1  # Reduced for less randomness
    z_short: 0.05
    
    # Topics
    scan_topic: scan
    map_topic: map
    
    # Initial pose settings
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      
    # Advanced parameters
    always_reset_initial_pose: false
    first_map_only: false
    laser_filter_weight: 0.4  # Weight for laser filter
    laser_z_hit: 0.95  # Weight for "hit" part of model
    laser_z_rand: 0.05  # Weight for random part of model
    
    # KLD sampling parameters
    kld_err: 0.01
    kld_z: 0.99
    
    # Augmented MCL parameters
    do_augmented_monte_carlo: true  # Enable augmented MCL
    
    # Exponential decay rate for the slow average weight filter
    alpha_slow: 0.001
    
    # Exponential decay rate for the fast average weight filter
    alpha_fast: 0.1
    
    # Threshold for the ratio of the fast and slow weight averages
    w_fast_slow_threshold: 0.5
    
    # Additional optimization parameters
    selective_resampling: true  # Only resample when needed
    
    # Adaptive parameters
    use_dynamic_range: true  # Dynamically adjust sensor ranges
    dynamic_range_factor: 1.5  # Factor for dynamic range adjustment
