controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 15.0  # Increased from 20.0 for more responsive control
    min_x_velocity_threshold: 0.05  # Reduced to allow smaller movements
    min_y_velocity_threshold: 0.05  # Reduced to allow smaller movements
    min_theta_velocity_threshold: 0.05  # Reduced to allow smaller rotations
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    odom_topic: "odom"
    cmd_vel_topic: "cmd_vel"

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3  # Reduced from 0.5 to detect smaller movements
      movement_time_allowance: 3.0  # Reduced from 5.0 for faster timeout

    # Goal checker parameters
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True

    # Controller parameters
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.8  # Increased from 0.4 for faster movement
      max_linear_accel: 1.5  # Increased from 0.8 for faster acceleration
      max_linear_decel: 1.5  # Increased from 0.8 for faster deceleration
      lookahead_dist: 0.8  # Increased from 0.6 to look further ahead at higher speeds
      min_lookahead_dist: 0.4  # Increased from 0.3 for stability at higher speeds
      max_lookahead_dist: 1.2  # Increased from 0.8 for better path following at higher speeds
      lookahead_time: 0.8  # Reduced from 1.0 for more responsive control
      rotate_to_heading_angular_vel: 1.5  # Increased from 0.8 for faster rotation
      transform_tolerance: 0.5
      use_velocity_scaled_lookahead_dist: true  # Changed to true for better performance at variable speeds
      min_approach_linear_velocity: 0.3  # Increased from 0.2 for faster approach
      approach_velocity_scaling_dist: 0.8  # Increased from 0.7 for smoother deceleration
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: true  # Changed to true for better obstacle avoidance
      regulated_linear_scaling_min_radius: 0.5
      regulated_linear_scaling_min_speed: 0.3  # Increased from 0.2 for faster minimum speed
      use_rotate_to_heading: true
      allow_reversing: false
      rotate_to_heading_min_angle: 0.785
      max_angular_accel: 2.0  # Increased from 1.0 for faster turning
      max_robot_pose_search_dist: 5.0
      use_interpolation: true  # Changed to true for smoother path following
